repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.1
  files: ^(declearn/|test/)
  exclude: .*_pb2.*py$
  hooks:
    - id: ruff
      args: ["--select", "I", "--fix"]
      name: "ruff sort and format imports"
    - id: ruff-format
      name: "ruff format"
      
    