site_name: Declearn
site_url: https://declearn.gitlabpages.inria.fr/

site_description: >-
  Declearn: a modular and extensible framework for Federated Learning

theme:
  name: material  #readthedocs

markdown_extensions:
  - pymdownx.arithmatex:  # mathjax
      generic: true

extra_javascript:
  # mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- autorefs
- search:
    lang: en
- literate-nav:
      nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          disable_private: true
          docstring_style: numpy
          docstring_section_style: "table"
          show_if_no_docstring: false  # show methods that inherit parent docs
          show_root_toc_entry: true
          show_signature_annotations: false  # useful for no-doc but ugly
