site_name: Declearn
site_url: https://magnet.gitlabpages.inria.fr/declearn/docs
site_dir: public

site_description: >-
  Declearn: a modular and extensible framework for Federated Learning

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt

repo_url: https://gitlab.inria.fr/magnet/declearn/declearn2
repo_name: magnet/declearn

markdown_extensions:
  - pymdownx.arithmatex:  # mathjax
      generic: true
  - pymdownx.superfences  # code coloring

extra:
  version:
    provider: mike
    canonical_version: latest

extra_javascript:
  # mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- autorefs
- search:
    lang: en
- literate-nav:
      nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          disable_private: true
          docstring_style: numpy
          docstring_section_style: "table"
          show_if_no_docstring: false
          show_root_toc_entry: true
          show_signature_annotations: false
