[tox]
requires =
    tox>=4
env_list = py311 # default env to run
install_command =
    python -I -m pip install -U {opts} {packages}


[testenv:py{311,312,313,314}]
description =
    "Default job, running all kinds of tests. Useful to be run locally by developers."
extras =
    all,tests
allowlist_externals =
    bash
commands=
    bash scripts/run_tests.sh lint_code
    bash scripts/run_tests.sh lint_tests
    bash scripts/run_tests.sh run_tests {posargs}
set_env =
    TF_FORCE_GPU_ALLOW_GROWTH=true  # prevent TensorFlow GPU pre-allocation
    XLA_PYTHON_CLIENT_PREALLOCATE=false  # prevent Jax GPU pre-allocation


[testenv:py311-ci]
# CI image is built with Declearn minimal supported Python version
# (3.11 for now) so we support only this version for this ci env
description =
    "CI-runner-adjusted job, running all kinds of tests under Python 3.11."
extras =
    grpc,haiku,tensorflow,websockets,tests
    # Matches "all,tests" without "torch" and "dp".
allowlist_externals =
    bash
basepython = python3.11
commands_pre =
    pip install "torch < 2.12" --index-url https://download.pytorch.org/whl/cu126
    # Note 1. Install torch explicitly with cuda 12.6 wheels to be compatible with the
    # GPU drivers installed on the CI server.
    # (Because cuda 13 is the default shipped version since torch 2.11.)
    # 
    # Note 2. Torch version is currently limited to 2.11, because torch 2.12
    # introduces a Python fatal error linked to torch model compilation and
    # torch dynamo.
    #
    # /!\ Is likely to change in the future, depending on the CI server config.
    pip install ".[dp]"
    # Install torch before DP dependencies. Otherwise, these dependencies
    # would install wrong torch backends.
commands =
    bash scripts/run_tests.sh lint_code
    bash scripts/run_tests.sh lint_tests
    bash scripts/run_tests.sh run_tests {posargs}
set_env =
    TF_FORCE_GPU_ALLOW_GROWTH=true  # prevent TensorFlow GPU pre-allocation
    XLA_PYTHON_CLIENT_PREALLOCATE=false  # prevent Jax GPU pre-allocation


[testenv:py{311,312,313,314}-tests]
description =
    "Individualized job to run unit and integration tests."
extras =
    all,tests
allowlist_externals =
    bash
commands=
    bash scripts/run_tests.sh run_tests {posargs}
set_env =
    TF_FORCE_GPU_ALLOW_GROWTH=true  # prevent TensorFlow GPU pre-allocation
    XLA_PYTHON_CLIENT_PREALLOCATE=false  # prevent Jax GPU pre-allocation


[testenv:py{311,312,313,314}-lint_code]
description =
    "Individualized job to run source code static analysis."
extras =
    all,tests
allowlist_externals =
    bash
commands =
    bash scripts/run_tests.sh lint_code


[testenv:py{311,312,313,314}-lint_tests]
description =
    "Individualized job to run test code static analysis."
extras =
    all,tests
allowlist_externals =
    bash
commands =
    bash scripts/run_tests.sh lint_tests
