[network]
protocol = "websockets"
host = "127.0.0.1"
port = 8765

[optim]
aggregator = "averaging" # The chosen aggregation strategy
server_opt = 1.0 # The server learning rate

    [optim.client_opt]
    lrate = 0.001 # The client learning rate
    modules = ["adam"] # The optimzer modules 

[run]
rounds = 10 # Number of training rounds

    [run.register]
    min_clients = 1
    max_clients = 6
    timeout = 5

    [run.training]
    n_epoch = 1 # Number of local epochs
    batch_size = 48 # Training batch size
    drop_remainder = false # Whether to drop the last trainig examples

    [run.evaluate]
    batch_size = 128 # Evaluation batch size


[experiment]
# all args for parse_data_folder


[model]
# information on where to find the model file

[data]
# all args from split_data argparser
scheme = "labels"