[network_server]
protocol = "websockets"
host = "127.0.0.1"
port = 8765

[network_client]
protocol = "websockets"
server_uri = "ws://localhost:8765"
name = "replaceme"

[optim]
aggregator = "averaging"
server_opt = 1.0

    [optim.client_opt]
    lrate = 0.001
    regularizers = ["lasso", {alpha = 0.1}]

[run]
rounds = 10

    [run.register]
    min_clients = 3

    [run.training]
    n_epoch = 1
    batch_size = 48
    drop_remainder = false



