[network_server]
protocol = "websockets"
host = "127.0.0.1"
port = 8765

[network_client]
protocol = "websockets"
server_uri = "ws://localhost:8765"
name = "replaceme"

[optim]
aggregator = "averaging" # The chosen aggregation strategy
server_opt = 1.0 # The server learning rate

    [optim.client_opt]
    lrate = 0.01 # The client learning rate
    regularizers = [["lasso", {alpha = 0.1}]] # The list of regularizer modules, each a list

[run]
rounds = 2 # Number of training rounds

    [run.register]
    min_clients = 1
    max_clients = 6
    timeout = 5

    [run.training]
    n_epoch = 1 # Number of local epochs
    batch_size = 48 # Training batch size
    drop_remainder = false # Whether to drop the last trainig examples

    [run.evaluate]
    batch_size = 128 # Evaluation batch size


