# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2\x89\x01\n\x0cMessageBoard\x12 \n\x04ping\x12\x0b.grpc.Empty\x1a\x0b.grpc.Empty\x12&\n\x04send\x12\r.grpc.Message\x1a\r.grpc.Message0\x01\x12/\n\x0bsend_stream\x12\r.grpc.Message\x1a\r.grpc.Message(\x01\x30\x01\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Message)
  })
_sym_db.RegisterMessage(Message)

_MESSAGEBOARD = DESCRIPTOR.services_by_name['MessageBoard']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=23
  _EMPTY._serialized_end=30
  _MESSAGE._serialized_start=32
  _MESSAGE._serialized_end=58
  _MESSAGEBOARD._serialized_start=61
  _MESSAGEBOARD._serialized_end=198
# @@protoc_insertion_point(module_scope)
